<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <PublishAot>false</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HYDRON.Core\HYDRON.Core.csproj" />
    <ProjectReference Include="..\..\src\HYDRON.Cryptography\HYDRON.Cryptography.csproj" />
    <ProjectReference Include="..\..\src\HYDRON.Database\HYDRON.Database.csproj" />
    <ProjectReference Include="..\..\src\HYDRON.Models\HYDRON.Models.csproj" />
    <ProjectReference Include="..\..\src\HYDRON.Validator\HYDRON.Validator.csproj" />
  </ItemGroup>

</Project>
